### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by wldmr-key** [Accvad/HandyMady#1]
Впредь обсуждаемые документы лучше аттачить в issue - мне будет удобнее

По тексту:

> повышение эффективности работы между самозанятыми и их покупателями

так не говорят

> 5.	Требования к программе или программному изделию

ты не знаешь, что у тебя - программа или программное изделие? ))

> 5.1.	Требования к функциональным характеристикам

отсутствуют упомянутые выше

> •	удобный интерфейс для выставления товаров и для аукциона;
•	возможность общения покупателей с самозанятыми;
•	отслеживание доставки;

> в качестве системы управления базой данных **рекомендуется** использовать PostgreSQL

В ТЗ слово рекомендуется исполнителем трактуется как "можно использовать, а можно и не использовать"

В остальном все приемлемо, вроде

**Comment by Accvad** [comment]
Пофиксил. Продолжаю работу

**Comment by wldmr-key** [comment]
в каком месте пофиксенное-то лежит?

**Comment by Accvad** [comment]
Я залил его сразу в репозиторий под версией 1.1
https://github.com/Accvad/HandyMady/blob/master/TechTask_v1.1.docx

**Comment by wldmr-key** [comment]
:) ах, я недогадливый :)

**Comment by Accvad** [comment]
Увеличил количество страниц https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_TechTask.docx

**Comment by wldmr-key** [comment]
да ну? что это было? куда смотреть-то?

**Comment by Accvad** [comment]
Я добавил в пунктах "Введение" и "Назначение разработки" подпункты и добавил инфы в "Требования к информационной и программной совместимости" и увеличил "Стадии и этапы разработки"

**Comment by wldmr-key** [comment]
а-а-а. Ну нормально
