### ISSUE TITLE
UML диаграммы

### ISSUE THREAD

**Issue by Accvad** [Accvad/HandyMady#11]
Максим Евгеньевич сказал мне сделать их более серьезными. Я так понимаю они заменят старые и придется обновить текст описания к ним. Вот что у меня получилось сделать:

![image](https://user-images.githubusercontent.com/43147847/83186460-36072d00-a135-11ea-9f9d-ea5c7fb63fca.png)
![image](https://user-images.githubusercontent.com/43147847/83186150-bed19900-a134-11ea-8c34-f6e3f60179ad.png)

**Comment by Accvad** [comment]
Вопрос: Исключить или оставить старые UML диаграммы со старым описанием, и просто добавить новые с новым описанием? Мне больше кажется первое т.к. будет похоже на тоже самое, но другим языком

**Comment by Accvad** [comment]
Старые UML и их старое описание
[Описание старых UML.docx](https://github.com/Accvad/HandyMady/files/4664434/UML.docx)

**Comment by wldmr-key** [comment]
старые исключить, конечно

**Comment by Accvad** [comment]
Тогда сделал)
