### ISSUE TITLE
Исследовательская часть

### ISSUE THREAD

**Issue by wldmr-key** [Accvad/HandyMady#2]
написать план

**Comment by wldmr-key** [comment]
и, где?

**Comment by Accvad** [comment]
Добавил альфу версию исследовательской части.
https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_RESEARCH_V1.0.docx

Владимир Юрьевич, а насколько от себя должна быть часть с описанием предметной области?
То есть можно ли брать определения чего-либо из интернета?

**Comment by wldmr-key** [comment]
)) с почином!

нормально. Осталось проанализировать аналоги и сделать выводы. Сразу советую обратить внимание на проблемы, которые ожидают организатора аукциона при недобросовестности участников
Разумеется можно (и нужно) брать определения откуда угодно. Но не забывать делать ссылки (и лучше это делать сразу при подготовке текста - самому же проще будет)

**Comment by Accvad** [comment]
Здравствуйте Владимир Юрьевич! Хотел спросить насчет сроков. Как я понял для конференции нужно успеть до 1 ноября, а какой срок чтобы выложиться в ринц? И если я опоздал, то возможно ли все равно как-то туда выложиться отдельно от НИРа?

**Comment by Accvad** [comment]
Исследовательская часть почти закончена, начинаю писать проектно-конструкторскую часть, а там и ИЧ полностью допишу. https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_RESEARCH.docx

**Comment by wldmr-key** [comment]
по концептуальной модели замечания - отдельно
Сценарий использования имеет смысл сделать отделье=ным подразделом и, возможно, проиллюстрировать. Обрати внимание, понятия, которые есть в сценарии использования совершенно не вяжутся с концептуальной моделью
И, да, где аналоги?

**Comment by Accvad** [comment]
Сделал множественные изменения, набралось 10 страниц 
https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_RESEARCH.docx

**Comment by wldmr-key** [comment]
в принципе, нормально. То, что нужно дописывать, сам показал. Система рейтингов и рекомендаций, как понимаешь, потребует изменений в схеме данных ((
В сценариях использования стоит более четко провести грань между ролями покупателей и продавцов. Ты правильно говоришь, что пользователь может выступить в любой роли. Но, зачес покупателю создавать магазин?!

**Comment by Accvad** [comment]
> Ты правильно говоришь, что пользователь может выступить в любой роли. Но, зачес покупателю создавать магазин?!

Вполне правильно. Ведь любой пользователь в любое удобное время может стать самозанятым и сделать свой магазин. Покупатель скорее выступает как рядовой пользователь(просто назван покупателем))

Систему рейтингов и рекомендаций я пока оставлю в подвешенном состоянии. Просто я не знаю как можно ее реализовать в схеме данных. С другой стороны пользователю вполне можно рекомендовать вещи по его оценкам и по его заказам(то есть получается схема не меняется), но остается вопрос как подбирать товары.

**Comment by Accvad** [comment]
С другой стороны если у продавца есть возможность покупать рекламу, то в схему данных нужно добавить сущность "реклама". Таким образом можно показывать людям вещи продавцов, которые купили рекламу, причем вещь должна совпадать с тем что человек покупал.

**Comment by Accvad** [comment]
Хотя появилась идея получше. Будет ли правильным сделать рекомендации по просмотрам? То есть если человек посмотрел брелки, то система будет ему показывать брелки. (получается нужно добавить сущность "просмотр"). Таким образом зайдя на сайт где есть бокс рекомендаций система просто ищет ему брелки самым высоким рейтингом.

**Comment by wldmr-key** [comment]
на данный момент - это перебор. В конце исследовательской части сделай раздел - дальнейшее развитие. И можешь записать туда этот поток сознания ))
Сейчас сдавай так как есть. Мысли у тебя совершенно правильные, но их стоило обдумать месяца на три раньше ))

**Comment by Accvad** [comment]
Готовая ИЧ. Описание концептуальной схемы мигрировало в описание логической)
https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_RESEARCH.docx

**Comment by wldmr-key** [comment]
пойдет...
