### ISSUE TITLE
НИР

### ISSUE THREAD

**Issue by wldmr-key** [Accvad/HandyMady#3]
пора определяться

**Comment by Accvad** [comment]
Честно сказать довольно сложно что-то придумать по теперь курсача/диплома, если только  какой-нибудь "выбор средств разработки для интернет платформы". Как крайний вариант начать писать про крипту что-нибудь.

**Comment by wldmr-key** [comment]
Я бы предложил что-нибудь поближе к твоей теме и жизненной практике. Как ты смотришь на вопрос определения соответствия хостинга требованиям к твоему (любому) приложению.

Вот, представь, ты написал свое приложение разворачиваешь его и выясняешь, что оно падает при трех пользователях. Или 30. Или 300...

Тема, что-то вроде исследование методов нагрузочного тестирования для определения оптимальной конфигурации хостинга (или приложения - зависит от того, чем тебе легче управлять)

**Comment by Accvad** [comment]
Звучит классно, попробую рассмотреть. А можно будет еще затронуть как выбирать хостинг вместе с нагрузочным тестированием?

**Comment by wldmr-key** [comment]
можно все )))

**Comment by Accvad** [comment]
Здравствуйте Владимир Юрьевич! Хотел спросить насчет сроков. Как я понял для конференции нужно успеть до 1 ноября, но какой срок чтобы выложиться в ринц? И если я опоздал, то возможно ли все равно как-то туда выложиться отдельно от НИРа?

**Comment by wldmr-key** [comment]
привет-привет! Я тебя совсем потерял. По поводу РИНЦ и выкладывания тебе лучше подойти к Е.Вершинину - он лучше владеет этим вопросом (так как я об этом знаю чуть меньше, чем ничего)
Ты бы, лучше, поведал чем ты полезным занимался последний месяц и какие у тебя планы на следующий

**Comment by Accvad** [comment]
Понял вас, спрошу его насчет этого. Виноват, но за месяц я перестал быть нулевым в плане создания веб проектов и уже начал делать макет, покажу в ближайшие дни. Я еще живой и за месяц планирую активную работу над всеми вопросами)

**Comment by Accvad** [comment]
Владимир Юрьевич, я наверное лучше сейчас напишу про нагрузочное тестирование)

**Comment by wldmr-key** [comment]
пиши

**Comment by Accvad** [comment]
[НИР.docx](https://github.com/Accvad/HandyMady/files/4001277/default.docx)
