### ISSUE TITLE
Разработать концептуальную схему

### ISSUE THREAD

**Issue by Accvad** [Accvad/HandyMady#6]

**Comment by Accvad** [comment]
Находится в новой версии ИЧ https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_RESEARCH.docx

**Comment by wldmr-key** [comment]
ужас-ужас!

У каждого магазина только один пользователь?
Заказ с магазином никак не связан?
Товар может быть только в одном заказе?
что-то ты совсем забыл про ER-диаграммы всё

И где все атрибуты, на которые ты ссылаешься в сценарии использования? Они к модели данных не относятся?

**Comment by Accvad** [comment]
На самом деле я смотрел на эту концептуальную схему немного под другим углом.
Связи подразумевают немного другое, я описал это подробнее на этой схеме. Ну и парочку вещей я поменял.
Я имел ввиду, что человек может создать несколько магазинов). 
Заказ с магазином пока что не связывал.
Товар может быть в нескольких заказах, ошибку учел.
Да, подзабыл немножко, получается вся диаграмма уже первоначально неправильна?

![image](https://user-images.githubusercontent.com/43147847/69755548-7f1bfb80-1169-11ea-9886-b2c7c22d2d97.png)

**Comment by wldmr-key** [comment]
в общем, приходи в понедельник. Будем учиться схемы рисовать ))

**Comment by Accvad** [comment]
Починил остальное. Я подумал, что если добавить атрибут "количество" в товары, думаю это решит проблему когда товара нет. Таким образом если товара нет, но будет количество будет нулем, а если товара не будет никогда, то NULL(или -1), таким образом товар будет скрыт, но при этом он останется в истории. 
![image](https://user-images.githubusercontent.com/43147847/70386685-c3e73400-19ac-11ea-8124-29cc64dd6ec2.png)

**Comment by wldmr-key** [comment]
о! уже правдоподобно!

**Comment by Accvad** [comment]
UPD 
![image](https://user-images.githubusercontent.com/43147847/70408604-d4091d00-1a59-11ea-920f-774c109ed203.png)

**Comment by wldmr-key** [comment]
хорошо
