### ISSUE TITLE
Проектно-конструкторская и Проектно-технологическая части

### ISSUE THREAD

**Issue by Accvad** [Accvad/HandyMady#7]

**Comment by Accvad** [comment]
По сути готовая конструкторская и технологическая части. Описание логической схемы я вырезал из описания концептуальной. А описание концептуальной я оставил миниатюрным.

https://github.com/Accvad/HandyMady/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%A1_HandyMadyRPZ_ENGINEERING_AND_PT.docx

**Comment by wldmr-key** [comment]
нормально. Но в логической схеме связь между Sales и Store представляется избыточной, так как она однозначно выражается транзитивно Sales-Goods-Store. Другое дело, если связи у тебя являются немодальными (что ты упорно избегаешь указывать на схеме) и распродажа может касаться всего ассортимента магазина...
