### ISSUE TITLE
IDEF0 диаграммы

### ISSUE THREAD

**Issue by Accvad** [Accvad/HandyMady#8]
Владимир Юрьевич, такой вопрос насчет IDEF0 диаграмм. Правильным ли будет сделать разные диаграммы на разный функционал? Как бы разделить его? Например вот диаграмма про регистрацию пользователя
![image](https://user-images.githubusercontent.com/43147847/71258403-22b29300-2347-11ea-89ee-fd4b53e6cf31.png)

**Comment by Accvad** [comment]
А еще придумал диаграмму которую точно нужно вставить или додумать. Но хорошая/правильная ли первая(про регистрацию) и стоит ли ее оставить?
![image](https://user-images.githubusercontent.com/43147847/71270956-e4779c80-2363-11ea-9b67-c6b1aca95ca4.png)

**Comment by wldmr-key** [comment]
скорее додумать, чем вставить )) - это не диаграмма процессов получилась...
Вот - легкая статья - https://habr.com/company/trinion/blog/322832/, вот - нормальная лекция (да и весь курс неплох, кстати) - https://sites.google.com/site/anisimovkhv/learning/pris/lecture/tema6  

вообще, литературы на эту тему полно...

**Comment by Accvad** [comment]
Я написал письменное разъяснение, может быть с ней будет более понятнее?)
[РПС_HandyMadyRPZ_ENGINEERING_AND_PT.docx](https://github.com/Accvad/HandyMady/files/3991474/_HandyMadyRPZ_ENGINEERING_AND_PT.docx)

**Comment by Accvad** [comment]
Если только между "Проверить наличие пользователя" и "добавление товара в позицию" добавить функцию предоставление списка товаров пользователю по поиску? Или дело в том, что пункты про добавление в заказ не функции вовсе? (просто я подумал что это то, что делает пользователь внутри системы)

**Comment by wldmr-key** [comment]
нет проблема не в непонятности. Почитай про нотацию

**Comment by Accvad** [comment]
Владимир Юрьевич, я прочитал по нотацию. Извините, я же правильно понимаю что все дело в том что все элементы должны быть расположены лесенкой, а главный элемент находиться левом верхнем углу?  А ну ещё блоки не везде правильно подписаны "добавление товара" =>"добавить товар". Просто проблемы же в оформлении или в изначальных элементах и задумке? Вроде нигде стрелки не забыл кроме тех где нет управляющих стрелок)

**Comment by wldmr-key** [comment]
Нет. Проблемы - по существу:
что у тебя было бы нарисовано на контекстной диаграмме?
что это у тебя за странные входы-выходы между блоками?
я бы два левых блока вообще убрал
а что это за последний блок? куда закрыть товар? ))

**Comment by Accvad** [comment]
Тогда наверное вот так, и такая контекстная диаграмма. 

> что это у тебя за странные входы-выходы между блоками?

Кривые стрелочки? Поправил)))

> а что это за последний блок? куда закрыть товар? ))

Произошла очепятка. Я имел в виду "закрытие заказа" :D

![image](https://user-images.githubusercontent.com/43147847/71311671-15260780-2432-11ea-853c-add11e2d1911.png)


![image](https://user-images.githubusercontent.com/43147847/71311673-19eabb80-2432-11ea-9974-5c5006770737.png)

**Comment by wldmr-key** [comment]
почти хорошо. Я бы исправил так:
1. Механизм везде один - база данных (не товаров, а системы). Он относится к 1 и 3 блокам
2. Чек должен генерироваться по правилам после оплаты заказа
3. в закрытии заказа продавец не участвует

**Comment by Accvad** [comment]
1) Вы имеете в виду механизм снизу вверх? Просто база данных же никак не управляет процессом. Он больше управляющий. 
2) Верно, но я имел в виду что пользователю и продавцу может отправляться отчет о закрытом заказе
3) Понял)

upd:
1) а потом я понял что я сказал, и перепрочел что означает стрелочка сверху вниз)))
Получается база данных снизу вверх так как она изменяется и принимает участие в процессе (если я правильно понял)

**Comment by Accvad** [comment]
Тогда получается вот так
![image](https://user-images.githubusercontent.com/43147847/71311933-54eeee00-2436-11ea-8a62-517aadd38af3.png)
![image](https://user-images.githubusercontent.com/43147847/71311934-58827500-2436-11ea-8a8b-0ae42b616e3c.png)

**Comment by Accvad** [comment]
Тогда получается вот так
![image](https://user-images.githubusercontent.com/43147847/71312175-e65f5f80-2438-11ea-9d57-be9fd7c2d53b.png)
![image](https://user-images.githubusercontent.com/43147847/71312177-ea8b7d00-2438-11ea-9169-d74799f42252.png)

**Comment by wldmr-key** [comment]
1. Нет я имел в виду механизм управления (контрол) и, поэтому, тебя запутал. Конечно, то что сверху вниз. Поэтому, с последними картинками ты погорячился )) 
и со своим апдейтом тоже ))
2. Отчет, на мой взгляд, это лишнее. Для продавца процесс заканчивается по окончании доставки. Он, конечно, может знакомиться со статусами и рейтингами, но это будет уже другой процесс.

**Comment by Accvad** [comment]
1) Ахах, понял исправил)
![image](https://user-images.githubusercontent.com/43147847/71312406-861ded00-243b-11ea-80c8-a2cd08003ca7.png)
![image](https://user-images.githubusercontent.com/43147847/71312407-8c13ce00-243b-11ea-8508-9711771f7490.png)

**Comment by wldmr-key** [comment]
Ну, не влияет продавец на закрытие заказа!!!
И товар уже доставлен! Для продавца процесс закончен на предпоследнем шаге!!

**Comment by Accvad** [comment]
Я думал я его удалил. Тогда вот финальный вариант.
![image](https://user-images.githubusercontent.com/43147847/71314275-3dbff880-2456-11ea-864d-cae05529a324.png)
![image](https://user-images.githubusercontent.com/43147847/71314276-43b5d980-2456-11ea-9117-0ccfd653499a.png)

**Comment by wldmr-key** [comment]
строго говоря, товар является доставленным независимо от функции закрытия заказа ))

**Comment by Accvad** [comment]
Кстати, имеет ли смысл вставить в рпз контекстную диаграмму вдобавок к диаграмме декомпозиции?

**Comment by wldmr-key** [comment]
вполне
