### ISSUE TITLE
Третья курсовая (предпредзащита)

### ISSUE THREAD

**Issue by Accvad** [Accvad/HandyMady#9]
Для удобства временно разделил на Diploma_Engineering_and_PT.docx и Diploma_Research.docx
Картинки и схемы для листов еще подправлю, ибо по ним было пару исправлений.
Все находится вот тут https://github.com/Accvad/HandyMady/tree/master/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B

**Comment by Accvad** [comment]
По изменениям:
1.1.3.5 - django заменен на asp.net core 
1.2 - django заменен на asp.net core 
1.7 - django заменен на asp.net core 
2.2 - django заменен на asp.net core и изменены скриншоты
3.1 - django заменен на asp.net core 
Вывод - django заменен на asp.net core

**Comment by Accvad** [comment]
Вопросы:
1) Получается я просто объединил два старых курсача в один(третий). возможно ли его сдать как курсач таким какой он есть или нужно что-то поправить/дополнить?
2) Нужно ли что-то делать с темой?
3) Получилось примерно 42 страницы учитывая всякие дипломные титульники и прочее. Нужно ли для курсача добавить еще или пока что хватит? Для диплома надо будет добавить однозначно потому что нужно от 45 до 60

**Comment by wldmr-key** [comment]
В начале ответы на вопросы:
1) да, можно попробовать сдать, но  предварительно стоит уточнить требования к курсовой работе (я их не знаю)
2) зачем?
3) насчет 42 страниц не уверен, так как части во многом дублируются. Если хочешь, неплохой исследовательской или конструкторской проблемой является поиск товара. Технологической - тестирование или развертывание, или какие-нибудь свежие части .Net, которые ты только что освоил

Теперь замечания:
по РТ
IDEF0 не декомпилируется, а декомпозируется
проверь склонения и спряжения в тексте
в логической схеме у тебя традиционно перепутаны направления стрелок. Ведь, было же когда-то правильно!!!

по рисеч более или менее нормально все...

**Comment by Accvad** [comment]
Логическую схему поправил. Оказалось больше чем я видел сначала потому что понял в чем я был не прав) ...кажется
![image](https://user-images.githubusercontent.com/43147847/81077121-39701580-8ef5-11ea-9f71-6ee1c3c2ad03.png)

**Comment by Accvad** [comment]
Получилось вот так.
https://github.com/Accvad/HandyMady/blob/master/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F_%D0%A5%D0%B0%D0%BB%D0%BC%D0%B5%D0%B4%D0%BE%D0%B2%D0%92%D0%9C_%D0%A1%D0%90%D0%9F%D0%A0%D0%91-81.docx

**Comment by Accvad** [comment]
Начинаю дописывать это все до диплома, для диплома, от диплома, для дипломов

**Comment by Accvad** [comment]
Продолжение обсуждения тут https://github.com/Accvad/HandyMady/issues/10
